{% set name = "eups" %}
{% set version = "2.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RobertLuptonTheGood/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ff3064a3db281fe15005bdcf9bbd780973471b3047d7462f4c5db82faee05d0a

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - tar
    - patch
    - git

  host:
    - python

  run:
    - python

about:
  home: https://github.com/RobertLuptonTheGood/eups
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl.txt
  summary: A version manager tracking product dependencies

extra:
  recipe-maintainers:
    - timj
    - ktlim
