{% set name = "eups" %}
{% set version = "2.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RobertLuptonTheGood/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3f08515ada84a6f4ba11549224864f6eb2f8b0507b6f90b2b3bba8bf60212f46

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - tar
    - patch
    - git

  host:
    - python

  run:
    - python

about:
  home: https://github.com/RobertLuptonTheGood/eups
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl.txt
  summary: A version manager tracking product dependencies

extra:
  recipe-maintainers:
    - timj
    - ktlim
