{% set name = "eups" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RobertLuptonTheGood/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 45c80ea8697b07ce9881bf263aad4f5ef41ea5ed4aae2469fb561f059129a199

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make

  host:
    - python

  run:
    - python

about:
  home: https://github.com/RobertLuptonTheGood/eups
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl.txt
  summary: A version manager tracking product dependencies

extra:
  recipe-maintainers:
    - gcomoretto
    - brianv0
    - ktlim
