{% set name = "eups" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RobertLuptonTheGood/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5e0352d134846ee6c7217dc43749aaa255ad07e03c86618b45c94f2a3e39535c

build:
  skip: true  # [win]
  number: 7

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - tar
    - patch
    - git

  host:
    - python

  run:
    - python

about:
  home: https://github.com/RobertLuptonTheGood/eups
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl.txt
  summary: A version manager tracking product dependencies

extra:
  recipe-maintainers:
    - timj
    - ktlim
